"""Authoring SDK package boundary for Syntara plugins."""

from syntara_plugin.contracts import ContractBundle, load_bundle

from .artifact import (
    OCI_ARTIFACT_TYPE,
    OCI_CONFIG_MEDIA_TYPE,
    OCI_CONTENT_BUNDLE_MEDIA_TYPE,
    OCI_PLUGIN_MANIFEST_MEDIA_TYPE,
    ArtifactBuildError,
    PluginArtifact,
    build_plugin_artifact,
)
from .artifact_archive import (
    OCI_LAYOUT_VERSION,
    ArtifactArchiveError,
    read_plugin_artifact_archive,
    write_plugin_artifact_archive,
)
from .catalog import (
    OCI_CATALOG_INDEX_ARTIFACT_TYPE,
    OCI_CATALOG_INDEX_CONFIG_MEDIA_TYPE,
    OCI_CATALOG_INDEX_CONTENT_MEDIA_TYPE,
    CatalogIndexArtifact,
    CatalogIndexArtifactBuildError,
    CatalogIndexUpdateError,
    build_catalog_index_artifact,
    merge_catalog_entry,
)
from .oci import OCI_IMAGE_MANIFEST_MEDIA_TYPE, OciBlob, OciDescriptor
from .registry import (
    CatalogIndexPublication,
    CatalogIndexPublicationError,
    CatalogIndexPublicationTarget,
    CatalogIndexPublisher,
    CatalogIndexSnapshot,
    OciRegistryResponse,
    OciRegistryTransport,
    PluginArtifactPublication,
    PluginArtifactPublicationError,
    PluginArtifactPublicationTarget,
    PluginArtifactPublisher,
    RegistryCredentials,
    UrllibOciRegistryTransport,
)
from .authoring import (
    BuildRequest,
    CompiledAsset,
    CompilationError,
    CompilationResult,
    Diagnostic,
    Plugin,
    SourceLocation,
    Target,
    compile_model,
    compile_workspace,
)

__all__ = [
    "ArtifactBuildError",
    "ArtifactArchiveError",
    "BuildRequest",
    "CatalogIndexArtifact",
    "CatalogIndexArtifactBuildError",
    "CatalogIndexUpdateError",
    "CatalogIndexPublication",
    "CatalogIndexPublicationError",
    "CatalogIndexPublicationTarget",
    "CatalogIndexPublisher",
    "CatalogIndexSnapshot",
    "CompiledAsset",
    "CompilationError",
    "CompilationResult",
    "ContractBundle",
    "Diagnostic",
    "OCI_ARTIFACT_TYPE",
    "OCI_CATALOG_INDEX_ARTIFACT_TYPE",
    "OCI_CATALOG_INDEX_CONFIG_MEDIA_TYPE",
    "OCI_CATALOG_INDEX_CONTENT_MEDIA_TYPE",
    "OCI_CONFIG_MEDIA_TYPE",
    "OCI_CONTENT_BUNDLE_MEDIA_TYPE",
    "OCI_IMAGE_MANIFEST_MEDIA_TYPE",
    "OCI_LAYOUT_VERSION",
    "OCI_PLUGIN_MANIFEST_MEDIA_TYPE",
    "OciBlob",
    "OciDescriptor",
    "OciRegistryResponse",
    "OciRegistryTransport",
    "Plugin",
    "PluginArtifact",
    "PluginArtifactPublication",
    "PluginArtifactPublicationError",
    "PluginArtifactPublicationTarget",
    "PluginArtifactPublisher",
    "RegistryCredentials",
    "SourceLocation",
    "Target",
    "UrllibOciRegistryTransport",
    "build_plugin_artifact",
    "build_catalog_index_artifact",
    "merge_catalog_entry",
    "compile_model",
    "compile_workspace",
    "load_bundle",
    "read_plugin_artifact_archive",
    "write_plugin_artifact_archive",
]
