# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from syntara_plugin.runtime.protocol import container_pb2 as syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in syntara_plugin/runtime/protocol/container_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContainerServiceStub(object):
    """The container ABI is the application-data channel between the Execution
    Plane and a plugin workload. It deliberately carries action identity and
    bounded JSON objects, never a container command or plaintext credential.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/syntara.container.v1alpha1.ContainerService/Execute',
                request_serializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.ExecutionEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/syntara.container.v1alpha1.ContainerService/Cancel',
                request_serializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.CancelRequest.SerializeToString,
                response_deserializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/syntara.container.v1alpha1.ContainerService/Health',
                request_serializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.HealthRequest.SerializeToString,
                response_deserializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.HealthResponse.FromString,
                _registered_method=True)


class ContainerServiceServicer(object):
    """The container ABI is the application-data channel between the Execution
    Plane and a plugin workload. It deliberately carries action identity and
    bounded JSON objects, never a container command or plaintext credential.
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.ExecuteRequest.FromString,
                    response_serializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.ExecutionEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.CancelRequest.FromString,
                    response_serializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.CancelResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.HealthRequest.FromString,
                    response_serializer=syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'syntara.container.v1alpha1.ContainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('syntara.container.v1alpha1.ContainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContainerService(object):
    """The container ABI is the application-data channel between the Execution
    Plane and a plugin workload. It deliberately carries action identity and
    bounded JSON objects, never a container command or plaintext credential.
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/syntara.container.v1alpha1.ContainerService/Execute',
            syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.ExecuteRequest.SerializeToString,
            syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.ExecutionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/syntara.container.v1alpha1.ContainerService/Cancel',
            syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.CancelRequest.SerializeToString,
            syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/syntara.container.v1alpha1.ContainerService/Health',
            syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.HealthRequest.SerializeToString,
            syntara__plugin_dot_runtime_dot_protocol_dot_container__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
